language: python
python:
  - "3.5"
matrix:
  include:
    # lint
    - python: "3.5"
      env: TOX_POSARGS="-e flake8"
    # core
    - python: "2.7"
      env: TOX_POSARGS="-e py27-core"
    - python: "3.4"
      env: TOX_POSARGS="-e py34-core"
    - python: "3.5"
      env: TOX_POSARGS="-e py35-core"
    # pyethereum 1.6.x
    - python: "2.7"
      env: TOX_POSARGS="-e py27-pyethereum16"
    - python: "3.4"
      env: TOX_POSARGS="-e py34-pyethereum16"
    - python: "3.5"
      env: TOX_POSARGS="-e py35-pyethereum16"
    # pyevm
    - python: "3.5"
      env: TOX_POSARGS="-e py35-pyevm"
cache:
  pip: true
install:
  - "travis_retry pip install pip setuptools --upgrade"
  - "travis_retry pip install tox"
script:
  - tox $TOX_POSARGS
after_script:
  - cat .tox/$TOX_POSARGS/log/*.log
