language: python
python:
  - "3.5"
env:
  matrix:
    # core
    - TOX_POSARGS="-e py27-core -e py34-core -e py35-core"
    # pyevm
    - TOX_POSARGS="-e py27-pyevm -e py34-pyevm -e py35-pyevm"
    # pyethereum 1.6.x
    - TOX_POSARGS="-e py27-pyethereum16 -e py34-pyethereum16 -e py35-pyethereum16"
    # pyethereum 2.0.x
    #- TOX_POSARGS="-e py27-pyethereum20 -e py34-pyethereum20 -e py35-pyethereum20"
    - TOX_POSARGS="-e flake8"
cache:
  pip: true
install:
  - "travis_retry pip install pip setuptools --upgrade"
  - "travis_retry pip install tox"
script:
  - tox $TOX_POSARGS
after_script:
  - cat .tox/$TOX_POSARGS/log/*.log
